version: "3"
networks:
  isolated-network:
services:
  mongo:
    ports:
      - "27017:27017"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DEBUG=server:*
      - NODE_ENV=development
  bpm:
    build:
      context: ./client/bpm
      dockerfile: Dockerfile
    volumes:
      - ./client/bpm:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:4200"